//! # morse-theory — Morse Theory on Manifolds
//!
//! Studies the topology of manifolds through the critical points of smooth
//! functions. Morse inequalities bound Betti numbers, and the Morse complex
//! recovers homology from gradient flows.

use std::collections::HashMap;

// ─── Critical Point ──────────────────────────────────────────────────────────

/// A non-degenerate critical point of a Morse function.
#[derive(Debug, Clone)]
pub struct CriticalPoint {
    pub id: usize,
    pub index: usize,       // Number of negative eigenvalues of Hessian
    pub value: f64,         // Function value
    pub position: Vec<f64>, // Coordinates on manifold
}

impl CriticalPoint {
    pub fn new(id: usize, index: usize, value: f64) -> Self {
        Self { id, index, value, position: Vec::new() }
    }

    pub fn at(mut self, coords: &[f64]) -> Self {
        self.position = coords.to_vec();
        self
    }

    /// Dimension contribution: a critical point of index k contributes a k-cell.
    pub fn cell_dimension(&self) -> usize {
        self.index
    }

    /// Is this a local minimum (index 0)?
    pub fn is_minimum(&self) -> bool {
        self.index == 0
    }

    /// Is this a local maximum?
    pub fn is_maximum(&self, dim: usize) -> bool {
        self.index == dim
    }
}

// ─── Morse Function ─────────────────────────────────────────────────────────

/// A Morse function with non-degenerate critical points.
#[derive(Debug, Clone)]
pub struct MorseFunction {
    pub name: String,
    pub dimension: usize,
    critical_points: Vec<CriticalPoint>,
}

impl MorseFunction {
    pub fn new(name: &str, dimension: usize) -> Self {
        Self { name: name.to_string(), dimension, critical_points: Vec::new() }
    }

    pub fn add_critical_point(&mut self, cp: CriticalPoint) {
        self.critical_points.push(cp);
    }

    pub fn critical_points(&self) -> &[CriticalPoint] {
        &self.critical_points
    }

    /// Number of critical points of given index.
    pub fn morse_number(&self, index: usize) -> usize {
        self.critical_points.iter().filter(|cp| cp.index == index).count()
    }

    /// Count critical points by index.
    pub fn morse_numbers(&self) -> Vec<usize> {
        let max_idx = self.critical_points.iter().map(|cp| cp.index).max().unwrap_or(0);
        (0..=max_idx).map(|k| self.morse_number(k)).collect()
    }

    /// Euler characteristic from Morse theory: χ = Σ(-1)^k μ_k
    pub fn euler_characteristic(&self) -> i64 {
        self.critical_points.iter()
            .map(|cp| if cp.index % 2 == 0 { 1i64 } else { -1i64 })
            .sum()
    }

    /// Total number of critical points.
    pub fn total_critical(&self) -> usize {
        self.critical_points.len()
    }
}

// ─── Morse Inequalities ─────────────────────────────────────────────────────

/// Morse inequalities relate critical points to Betti numbers.
pub struct MorseInequalities;

impl MorseInequalities {
    /// Weak Morse inequality: μₖ ≥ βₖ for all k.
    /// Returns (morse_number, betti_number, satisfied).
    pub fn weak_inequality(morse: &[usize], betti: &[usize]) -> Vec<(usize, usize, bool)> {
        let n = morse.len().max(betti.len());
        (0..n).map(|k| {
            let mk = morse.get(k).copied().unwrap_or(0);
            let bk = betti.get(k).copied().unwrap_or(0);
            (mk, bk, mk >= bk)
        }).collect()
    }

    /// Strong Morse inequality: Σ_{j≤k} (-1)^{k-j} μⱼ ≥ Σ_{j≤k} (-1)^{k-j} βⱼ
    pub fn strong_inequality(morse: &[usize], betti: &[usize]) -> bool {
        let n = morse.len().max(betti.len());
        for k in 0..n {
            let lhs: i64 = (0..=k)
                .map(|j| {
                    let sign = if (k - j) % 2 == 0 { 1i64 } else { -1i64 };
                    sign * morse.get(j).copied().unwrap_or(0) as i64
                })
                .sum();
            let rhs: i64 = (0..=k)
                .map(|j| {
                    let sign = if (k - j) % 2 == 0 { 1i64 } else { -1i64 };
                    sign * betti.get(j).copied().unwrap_or(0) as i64
                })
                .sum();
            if lhs < rhs {
                return false;
            }
        }
        true
    }
}

// ─── Morse Complex ───────────────────────────────────────────────────────────

/// The Morse complex: chain groups generated by critical points,
/// boundary maps from gradient flow lines.
#[derive(Debug, Clone)]
pub struct MorseComplex {
    pub dimension: usize,
    pub groups: Vec<Vec<usize>>,   // groups[k] = list of critical point IDs of index k
    pub boundary: HashMap<(usize, usize), i64>, // boundary[(k, id)] → count of gradient lines
}

impl MorseComplex {
    pub fn from_morse_function(mf: &MorseFunction) -> Self {
        let max_idx = mf.critical_points.iter().map(|cp| cp.index).max().unwrap_or(0);
        let mut groups = vec![Vec::new(); max_idx + 1];

        for cp in &mf.critical_points {
            groups[cp.index].push(cp.id);
        }

        Self {
            dimension: mf.dimension,
            groups,
            boundary: HashMap::new(),
        }
    }

    /// Rank of k-th chain group = number of critical points of index k.
    pub fn rank(&self, k: usize) -> usize {
        self.groups.get(k).map(|g| g.len()).unwrap_or(0)
    }

    /// Euler characteristic from the complex.
    pub fn euler_characteristic(&self) -> i64 {
        (0..self.groups.len())
            .map(|k| {
                let sign = if k % 2 == 0 { 1i64 } else { -1i64 };
                sign * self.rank(k) as i64
            })
            .sum()
    }
}

// ─── Handle Attachment ───────────────────────────────────────────────────────

/// Build a manifold by attaching handles corresponding to critical points.
#[derive(Debug, Clone)]
pub struct HandleAttachment {
    pub index: usize,
    pub dimension: usize,
    pub attached_at_value: f64,
}

impl HandleAttachment {
    /// Create handle from a critical point.
    pub fn from_critical_point(cp: &CriticalPoint, manifold_dim: usize) -> Self {
        Self {
            index: cp.index,
            dimension: manifold_dim,
            attached_at_value: cp.value,
        }
    }

    /// Handle dimension = index of critical point.
    pub fn handle_dimension(&self) -> usize {
        self.index
    }
}

/// Build manifold from a sequence of handle attachments.
pub fn build_manifold(critical_points: &[CriticalPoint], dim: usize) -> Vec<HandleAttachment> {
    let mut handles: Vec<HandleAttachment> = critical_points.iter()
        .map(|cp| HandleAttachment::from_critical_point(cp, dim))
        .collect();
    handles.sort_by(|a, b| a.attached_at_value.partial_cmp(&b.attached_at_value).unwrap());
    handles
}

#[cfg(test)]
mod tests {
    use super::*;

    fn torus_morse_function() -> MorseFunction {
        // Torus has 4 critical points: min (0), 2 saddles (1), max (2)
        let mut mf = MorseFunction::new("height on torus", 2);
        mf.add_critical_point(CriticalPoint::new(0, 0, 0.0));    // minimum
        mf.add_critical_point(CriticalPoint::new(1, 1, 1.0));    // saddle
        mf.add_critical_point(CriticalPoint::new(2, 1, 2.0));    // saddle
        mf.add_critical_point(CriticalPoint::new(3, 2, 3.0));    // maximum
        mf
    }

    #[test]
    fn test_critical_point() {
        let cp = CriticalPoint::new(0, 2, 1.5);
        assert_eq!(cp.cell_dimension(), 2);
        assert!(cp.is_minimum() == false);
    }

    #[test]
    fn test_minimum() {
        let cp = CriticalPoint::new(0, 0, 0.0);
        assert!(cp.is_minimum());
        assert!(!cp.is_maximum(2));
    }

    #[test]
    fn test_morse_numbers() {
        let mf = torus_morse_function();
        assert_eq!(mf.morse_number(0), 1);
        assert_eq!(mf.morse_number(1), 2);
        assert_eq!(mf.morse_number(2), 1);
    }

    #[test]
    fn test_euler_characteristic_torus() {
        let mf = torus_morse_function();
        // χ(T²) = 1 - 2 + 1 = 0
        assert_eq!(mf.euler_characteristic(), 0);
    }

    #[test]
    fn test_euler_characteristic_sphere() {
        let mut mf = MorseFunction::new("height on S²", 2);
        mf.add_critical_point(CriticalPoint::new(0, 0, -1.0));
        mf.add_critical_point(CriticalPoint::new(1, 1, 0.0));
        mf.add_critical_point(CriticalPoint::new(2, 2, 1.0));
        // χ(S²) = 1 - 1 + 1 = 1
        assert_eq!(mf.euler_characteristic(), 1);
    }

    #[test]
    fn test_weak_morse_inequality() {
        let morse = vec![1, 2, 1]; // μ₀=1, μ₁=2, μ₂=1 (torus)
        let betti = vec![1, 2, 1]; // β₀=1, β₁=2, β₂=1 (torus)
        let results = MorseInequalities::weak_inequality(&morse, &betti);
        assert!(results.iter().all(|(_, _, s)| *s));
    }

    #[test]
    fn test_weak_inequality_violated() {
        let morse = vec![1, 1, 1]; // not enough saddles
        let betti = vec![1, 2, 1];
        let results = MorseInequalities::weak_inequality(&morse, &betti);
        assert!(!results[1].2); // μ₁=1 < β₁=2
    }

    #[test]
    fn test_strong_morse_inequality() {
        let morse = vec![1, 2, 1];
        let betti = vec![1, 2, 1];
        assert!(MorseInequalities::strong_inequality(&morse, &betti));
    }

    #[test]
    fn test_morse_complex() {
        let mf = torus_morse_function();
        let complex = MorseComplex::from_morse_function(&mf);
        assert_eq!(complex.rank(0), 1);
        assert_eq!(complex.rank(1), 2);
        assert_eq!(complex.rank(2), 1);
    }

    #[test]
    fn test_morse_complex_euler() {
        let mf = torus_morse_function();
        let complex = MorseComplex::from_morse_function(&mf);
        assert_eq!(complex.euler_characteristic(), 0);
    }

    #[test]
    fn test_handle_attachment() {
        let mf = torus_morse_function();
        let handles = build_manifold(mf.critical_points(), 2);
        assert_eq!(handles.len(), 4);
        assert_eq!(handles[0].attached_at_value, 0.0); // sorted by value
    }

    #[test]
    fn test_handle_dimensions() {
        let cp = CriticalPoint::new(0, 1, 1.0);
        let h = HandleAttachment::from_critical_point(&cp, 3);
        assert_eq!(h.handle_dimension(), 1);
    }

    #[test]
    fn test_maximum() {
        let cp = CriticalPoint::new(0, 2, 5.0);
        assert!(cp.is_maximum(2));
        assert!(!cp.is_maximum(3));
    }

    #[test]
    fn test_morse_function_total() {
        let mf = torus_morse_function();
        assert_eq!(mf.total_critical(), 4);
    }
}
